### ISSUE TITLE
Hide the 'files' tab to non admins

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_core#220]
The files tab is pretty much meaningless to content designers, they need the 'media' tab. 

Let's hide it for all, except admin users.

![Image](https://github.com/user-attachments/assets/4510b424-7516-44a8-b8e4-90f51d937720)

**Comment by willguv** [comment]
@MariosORION this is related to the tab weights work you've just done, so might be quick for you - thanks

**Comment by markconroy** [comment]
@willguv we have a PR for this - https://github.com/localgovdrupal/localgov_core/pull/221 - but the other core team members think we should not do this for existing sites.

**Comment by willguv** [comment]
OK, we should explain how to do it though. 

Can it be for new installs?

Is making this change in config a dev job?

**Comment by markconroy** [comment]
I think it would be good to have it removed for new installs.

For existing sites, it would then mean a developer would have to remove that permission for whatever current roles we don't want it on.

Here's the Merge Tuesday notes for it: https://github.com/localgovdrupal/localgov_core/pull/221#issuecomment-2135025049

**Comment by MariosORION** [comment]
Thanks both @markconroy, assigning back to @willguv for now.

**Comment by willguv** [comment]
@markconroy Does this remove the ability for content designers to fully delete files? If so, we will need to review

@finnlewis mentioned caching causing problems. Maria at Bracknell Forest mentioned the need to instantly delete files when it's really necessary, and has a fix

@stephen-cox  mentioned a setting for how long temporary files are kept. When a file is deleted in Drupal it's marked for deletion and done later

Andy says they have a checkbox for users to select when deleting a media item to delete the underlying files as well

**Comment by andybroomfield** [comment]
Media file delete?
(Might be in the default install already).

![Image](https://github.com/user-attachments/assets/48b25aff-906f-4c7f-aa84-463c9a7586c9)

**Comment by andybroomfield** [comment]
The module is called [media file delete](https://www.drupal.org/project/media_file_delete)

**Comment by markconroy** [comment]
Looks like Media file delete module might be a good addition to our CMS

**Comment by LizziCBFC** [comment]
Maria asked me to add some comments about the file deletion issue we had at Bracknell where files took 6 hours to delete.

On deleting a file, it turned into a 'temporary' file.

This was the comment from WebCurl:

_Temporary files are deleted during cron runs if they're older than 6 hours. (6 hours is the minimum built-in option that Drupal provides). This delay is designed so that newly uploaded files which have not yet been saved to a permanent location are not removed prematurely.

Rather than forcing the delay to be shorter and potentially causing issues, it might be better to make file deletion happen directly instead of changing to temporary and waiting.

The file deletion option is currently provided by a contrib module, https://www.drupal.org/project/file_delete

However, file deletion functionality is also available in Drupal core since 10.1 (making the module essentially obsolete!). I'm not sure which method the core file deletion action uses - if this deletes immediately then I would recommend switching._ 

**Follow up:**

Drupal core's file deletion option deletes immediately rather than switching to temporary. 

We switched to using that. The only issue was that you can now delete files even when in use under 'media' so you have to be more careful about deleting in-use items.

-----

On another note, I find the files tab really useful as it provides better information such as file type and size.

**Comment by willguv** [comment]
@markconroy did you change this to move the 'files' tab rather than delete it? Let's catch up at the PG about it

**Comment by markconroy** [comment]
Yes, I have a PR for it https://github.com/localgovdrupal/localgov_core/pull/221

But there's a question at the end of that waiting for you to reply.

**Comment by willguv** [comment]
Product Group notes:

Update hook for all, release notes and newsletter

**Comment by andybroomfield** [comment]
![94neex](https://github.com/user-attachments/assets/e7f3758f-8555-42b6-9043-db82e53756db)

**Comment by andybroomfield** [comment]
<img src="https://github.com/user-attachments/assets/d069a169-c164-4466-afa1-11e8c14dafc2" alt="Oprah Winfery meme template with the text - Your getting an update hook! your getting an update hook! Everyones getting an update hook!">
